package com.easy1staking.shithole.config;

import com.bloxbean.cardano.client.address.Address;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.address.Credential;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.util.HexUtil;
import com.easy1staking.shithole.blueprint.generated.jar.JarSpendValidator;
import com.easy1staking.shithole.blueprint.generated.listing.ListingSpendValidator;
import com.easy1staking.shithole.blueprint.generated.marketplace.MarketplaceSpendValidator;
import com.easy1staking.shithole.blueprint.generated.wantedlisting.WantedListingSpendValidator;
import com.easy1staking.shithole.entity.ConfigEntity;
import com.easy1staking.shithole.entity.CuratedCollectionEntity;
import com.easy1staking.shithole.repository.ConfigRepository;
import com.easy1staking.shithole.repository.CuratedCollectionRepository;
import com.easy1staking.shithole.service.ListingScriptAddressDeriver;
import com.easy1staking.shithole.service.MarketplaceScriptAddressDeriver;
import com.easy1staking.shithole.service.MarketplaceScriptAddressDeriver.MarketplaceArtifacts;
import com.easy1staking.shithole.service.WantedListingScriptAddressDeriver;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Function;

/**
 * Single source of truth for all script addresses + on-chain hashes the
 * BE derives from {@code contracts/plutus.json} at startup.
 *
 * <p>Two purposes:
 *
 * <ol>
 *   <li><b>Boot-time banner.</b> Logs every derived address + hash in a
 *       single multi-line block so an operator can verify at a glance
 *       that the running JVM agrees with the FE / explorer / wallet
 *       about which on-chain addresses are in play. The drift that bit
 *       us on 2026-05-29 (BE running with stale CCL-generated bytecode
 *       constants while the FE used the rebuilt {@code plutus.json})
 *       would have been instantly visible at boot.</li>
 *   <li><b>Single snapshot.</b> Exposes {@link #getSnapshot()} so future
 *       endpoints (e.g. {@code GET /api/market/manifest}) and other
 *       BE-internal callers can read the canonical derivation without
 *       re-running the UPLC apply chain themselves.</li>
 * </ol>
 *
 * <h3>What gets derived</h3>
 *
 * <p><b>Static (one per network, parameterized on {@code admin_pkh} only):</b>
 * jar applied hash + address, marketplace applied hash + address. Driven
 * by {@code shithole.market.admin-pkh}. Unset → marketplace section
 * shows "DISABLED" and the rest of the BE still boots.
 *
 * <p><b>Per curated collection (parameterized on {@code config_nft_policy}):</b>
 * config script address, listing script address, wanted-listing script
 * address, plus the stored treasury bech32 and admin pkh from the
 * matching {@code configs} row.
 *
 * <h3>What does NOT get derived here</h3>
 *
 * <p>This is a snapshot at boot, NOT a live registry. New curated
 * collections registered via {@code POST /api/configs} after startup
 * land in
 * {@link com.easy1staking.shithole.indexer.WatchAddressRegistry} via
 * its {@link com.easy1staking.shithole.indexer.ConfigRegisteredEvent}
 * listener; this class doesn't react to them. The trade-off is
 * acceptable because the banner's job is "what does the BE think on
 * day-one boot", not "live state."
 *
 * <h3>Unparameterized hashes (printed alongside derived ones)</h3>
 *
 * <p>{@link JarSpendValidator#HASH} etc. are the hashes of the
 * <em>unapplied</em> bytecode as compiled into the CCL annotation-
 * processor output. They MUST match
 * {@code git show HEAD:contracts/plutus.json | jq '.validators[].hash'}
 * — if they don't, the BE was built against a stale {@code plutus.json}
 * and you need to re-run {@code ./gradlew clean build} from {@code api/}.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class ChainAddressManifest {

    private final Network appNetwork;
    private final MarketplaceScriptAddressDeriver marketplaceDeriver;
    private final ListingScriptAddressDeriver listingDeriver;
    private final WantedListingScriptAddressDeriver wantedDeriver;
    private final CuratedCollectionRepository curatedRepository;
    private final ConfigRepository configRepository;

    @Value("${app.network:mainnet}")
    private String networkName;

    private volatile Snapshot snapshot = Snapshot.empty();

    @PostConstruct
    void deriveAndLog() {
        Optional<MarketplaceArtifacts> marketplace = Optional.empty();
        try {
            marketplace = marketplaceDeriver.deriveArtifacts();
        } catch (RuntimeException e) {
            log.error("ChainAddressManifest: marketplace derivation failed: {}", e.getMessage(), e);
        }

        List<PerCollection> collections;
        try {
            collections = curatedRepository.findAll().stream()
                    .map(this::derivePerCollection)
                    .filter(Objects::nonNull)
                    .toList();
        } catch (RuntimeException e) {
            log.error("ChainAddressManifest: curated-collection enumeration failed: {}",
                    e.getMessage(), e);
            collections = List.of();
        }

        snapshot = new Snapshot(networkName.toLowerCase(Locale.ROOT), marketplace, collections);
        logBanner(snapshot);
    }

    /** Current snapshot. Mutates once at boot; constant for the process lifetime. */
    public Snapshot getSnapshot() {
        return snapshot;
    }

    private PerCollection derivePerCollection(CuratedCollectionEntity row) {
        String policy = row.getConfigNftPolicy();
        if (policy == null || policy.isBlank()) return null;

        String configAddr = deriveConfigScriptAddress(policy);
        String listingAddr = safeDerive("listing", policy, listingDeriver::deriveAddress);
        String wantedAddr = safeDerive("wanted_listing", policy, wantedDeriver::deriveAddress);

        String treasuryAddr = null;
        String adminPkh = null;
        try {
            ConfigEntity cfg = configRepository.findById(policy).orElse(null);
            if (cfg != null) {
                treasuryAddr = cfg.getTreasuryAddrBech32();
                adminPkh = cfg.getAdminPkh();
            }
        } catch (RuntimeException e) {
            log.warn("ChainAddressManifest: config lookup failed for policy {}: {}",
                    policy, e.getMessage());
        }

        return new PerCollection(
                row.getSlug(),
                policy,
                row.getCollectionPolicyId(),
                configAddr,
                listingAddr,
                wantedAddr,
                treasuryAddr,
                adminPkh);
    }

    private String safeDerive(String kind, String policy, Function<String, String> fn) {
        try {
            return fn.apply(policy);
        } catch (RuntimeException e) {
            log.warn("ChainAddressManifest: {} address derivation failed for policy {}: {}",
                    kind, policy, e.getMessage());
            return null;
        }
    }

    /**
     * The config validator's payment credential IS its own script hash —
     * which is also {@code config_nft_policy} by construction (the
     * config validator is a multi-handler that both spends and mints).
     */
    private String deriveConfigScriptAddress(String configNftPolicyHex) {
        try {
            byte[] hash = HexUtil.decodeHexString(configNftPolicyHex);
            Credential cred = Credential.fromScript(hash);
            Address addr = AddressProvider.getEntAddress(cred, appNetwork);
            return addr.toBech32();
        } catch (RuntimeException e) {
            log.warn("ChainAddressManifest: config script address derivation failed for policy {}: {}",
                    configNftPolicyHex, e.getMessage());
            return null;
        }
    }

    private void logBanner(Snapshot s) {
        String sep = "=".repeat(78);
        StringBuilder sb = new StringBuilder("\n").append(sep).append('\n')
                .append("SHITHOLE chain-address manifest").append('\n')
                .append("network=").append(s.network())
                .append(" networkId=").append(appNetwork.getNetworkId())
                .append(" magic=").append(appNetwork.getProtocolMagic()).append('\n')
                .append(sep).append('\n');

        // Unparameterized hashes — match these against
        // contracts/plutus.json to catch stale CCL-generated bytecode.
        sb.append("unparameterized validator hashes (compare to plutus.json):").append('\n');
        sb.append(line("  jar.spend",             JarSpendValidator.HASH));
        sb.append(line("  marketplace.spend",     MarketplaceSpendValidator.HASH));
        sb.append(line("  listing.spend",         ListingSpendValidator.HASH));
        sb.append(line("  wanted_listing.spend",  WantedListingSpendValidator.HASH));
        sb.append("-".repeat(78)).append('\n');

        // Static (admin_pkh-only) marketplace + jar.
        if (s.marketplace().isPresent()) {
            MarketplaceArtifacts m = s.marketplace().get();
            sb.append("marketplace (singleton, parameterized on admin_pkh):").append('\n');
            sb.append(line("  admin_pkh",                  m.adminPkhHex()));
            sb.append(line("  jar_script_hash (applied)",  m.jarScriptHashHex()));
            sb.append(line("  jar_address",                m.jarAddress()));
            sb.append(line("  marketplace_hash (applied)", m.marketplaceScriptHashHex()));
            sb.append(line("  marketplace_address",        m.marketplaceAddress()));
        } else {
            sb.append("marketplace                 DISABLED (no shithole.market.admin-pkh)").append('\n');
        }
        sb.append("-".repeat(78)).append('\n');

        // Per-collection snapshot at boot.
        if (s.collections().isEmpty()) {
            sb.append("per-collection              (none registered yet)").append('\n');
        } else {
            sb.append("per-collection (").append(s.collections().size()).append(" curated):").append('\n');
            for (PerCollection p : s.collections()) {
                sb.append("  slug=").append(p.slug()).append('\n');
                sb.append(line("    config_nft_policy",    p.configNftPolicy()));
                sb.append(line("    collection_policy_id", p.collectionPolicyId()));
                sb.append(line("    config_script_addr",   nz(p.configScriptAddress())));
                sb.append(line("    listing_script_addr",  nz(p.listingScriptAddress())));
                sb.append(line("    wanted_listing_addr",  nz(p.wantedListingAddress())));
                sb.append(line("    treasury_addr",        nz(p.treasuryAddressBech32())));
                sb.append(line("    config.admin_pkh",     nz(p.adminPkhHex())));
            }
        }
        sb.append(sep);
        log.info(sb.toString());
    }

    /** Align label/value pairs with a 30-column label gutter. */
    private static String line(String label, String value) {
        int gutter = 30;
        StringBuilder sb = new StringBuilder(label);
        while (sb.length() < gutter) sb.append(' ');
        sb.append(value == null ? "<missing>" : value).append('\n');
        return sb.toString();
    }

    private static String nz(String s) {
        return s == null ? "<missing>" : s;
    }

    /** Boot-time snapshot of every chain address the BE derived from
     *  {@code plutus.json}. Immutable for the process lifetime. */
    public record Snapshot(
            String network,
            Optional<MarketplaceArtifacts> marketplace,
            List<PerCollection> collections) {
        static Snapshot empty() {
            return new Snapshot("unknown", Optional.empty(), List.of());
        }
    }

    /** Per-collection derived view. Fields may be null when the matching
     *  DB lookup or UPLC derive failed at boot (logged as warnings). */
    public record PerCollection(
            String slug,
            String configNftPolicy,
            String collectionPolicyId,
            String configScriptAddress,
            String listingScriptAddress,
            String wantedListingAddress,
            String treasuryAddressBech32,
            String adminPkhHex) {
    }
}
