-- V1_0_4 — relax nft_traits.asset_name length CHECK.
--
-- V1_0_3 enforced `octet_length(asset_name) = 28`, which is wrong: CIP-25
-- asset names are 0-32 bytes per the spec, and the actual minter picks the
-- length per collection. Hosky CashGrab names are 22 bytes
-- ("HOSKYCashGrab" + 9-digit serial), so the strict-28 constraint would
-- reject every real Hosky asset_name on insert.
--
-- This migration drops the strict-28 CHECK and replaces it with the proper
-- CIP-25 range. Existing PK + GIN index untouched.
--
-- Constraint name on the V1_0_3-created CHECK was auto-generated by
-- Postgres ('nft_traits_asset_name_check'). If a future migration needs to
-- alter it again, name it explicitly via CONSTRAINT … CHECK (…).

ALTER TABLE nft_traits DROP CONSTRAINT nft_traits_asset_name_check;
ALTER TABLE nft_traits
    ADD CONSTRAINT nft_traits_asset_name_len_check
    CHECK (octet_length(asset_name) BETWEEN 0 AND 32);
